[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "DQk2cmc2UgS66LQbebkKetHgnsMbh4zvLpD5ocyZubb1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/bhaskarkh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
